apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/inference_sre?sslmode=disable"
