apiVersion: v1
kind: Service
metadata:
  name: inference-worker
  labels:
    app: inference-worker
spec:
  type: ClusterIP
  selector:
    app: inference-worker
  ports:
  - name: http
    port: 8000
    targetPort: http
